[workspace]

resolver = "2"

members = ["crates/*"]

[workspace.package]
version = "0.16.0"
edition = "2021"
authors = ["Georgios Moschovitis <george.moschovitis@gmail.com>"]
license = "Apache-2.0"

[workspace.dependencies]
tan = { path = "../tan", version = "0.16" }
